---
AWSTemplateFormatVersion: "2010-09-09"
#
# This checks how lamdba logs to cloudwatch logs
#
# -----------------------------------------------------------------------------
Parameters:
# -----------------------------------------------------------------------------
  Tag:
    Type: String
    Description: some artifical tag value to trigger an update of the cf
    Default: ''

# -----------------------------------------------------------------------------
Resources:
# -----------------------------------------------------------------------------
  Function:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        ZipFile: |
          import json
          def lambda_handler(event, context):
            return {
                "statusCode": 200,
                "body": json.dumps('Hello from Lambda!')
            }

      Description: Small function to test logging
      Handler: index.lambda_handler
      Role: !GetAtt LambdaExecutionRole.Arn
      Runtime: python3.6
      Tags:
        -
          Key: usecase
          Value: test
        -
          Key: foo
          Value: !Ref Tag

  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - lambda.amazonaws.com
          Action:
          - sts:AssumeRole
      Path: "/"
      Policies:
      - PolicyName: root
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action:
            - logs:*
            Resource: arn:aws:logs:*:*:*
# -----------------------------------------------------------------------------
Outputs:
# -----------------------------------------------------------------------------
  Function:
    Value: !Ref Function
