#!/usr/bin/env python

import click
import aws_truth_teller.dynamodb as dynamodb


@click.group()
def cli():
    pass


@cli.command()
def test_restore():
    dynamodb.how_to_restore_a_cloudformation_managed_table()


@cli.command()
def cleanup():
    dynamodb.cleanup()


if __name__ == '__main__':
    cli()
